const locationData = {
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Thane",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Satara",
    "Sangli",
  ],
  Karnataka: [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Ballari",
    "Kalaburagi",
    "Tumakuru",
    "Shivamogga",
  ],
  Punjab: [
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Gurdaspur",
    "Firozpur",
    "Sangrur",
    "Moga",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur Nagar",
    "Varanasi",
    "Prayagraj",
    "Agra",
    "Ghaziabad",
    "Noida",
    "Meerut",
    "Gorakhpur",
    "Bareilly",
  ],
};

export default locationData;
